### ISSUE TITLE
Unable to tag some conversations

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#7] opened 2017-05-26 19:20 UTC
### DESCRIPTION
Tagging does not work for some conversations

### STEPS
1. This seems fairly random. Some conversations can be tagged, some can't.

### EXPECTED
All conversations containing at least one message sent or received since the app was installed should be able to be tagged. If the conversation has only old messages, it is okay to show a pop up stating the conversation cannot be tagged (see issue #3).

### OBSERVATIONS
For unknown reasons, some conversations cannot be tagged. One hypothesis is that they cannot be tagged until they have been fully synced with the client and server databases, though this is untested.

**Comment by seanjaffe1** [comment] 2017-05-26 20:34
We found the cause to be failure for the query and update to use the same format for the address

**Comment by stcastle** [comment] 2017-06-12 21:58
@seanjaffe1  did you fix this?

**Comment by seanjaffe1** [comment] 2017-06-12 22:51
I think so. see https://github.com/uw-ictd/dfs-phishing-sms-client/commit/ba5f0bdd2cad57a91ec91d86d78cfb2cb5d5b139

**Comment by fahadp** [comment] 2017-06-15 03:20
I fixed the error in Sean's fix. @stcastle please test it to verify that it is indeed resolved.

**Comment by fahadp** [comment] 2017-06-16 21:41
Closing this issue as we have the fix in code.

**Closed as completed by fahadp** 2017-06-16 21:41 UTC
Labels: bug, Level-Blocker
